[package]
name = "rgpui-character"
version = "0.2.0"
edition = "2024"
publish = true
description = "rgpui 桌宠与 UI 角色运行时系统"
license = "Apache-2.0"
repository = "https://github.com/launcher-rs/rgpui-character.git"


[lib]
path = "src/rgpui_character.rs"
doctest = false

[dependencies]
thiserror = "2.0.12"

[dev-dependencies]
anyhow = "1.0.86"
rgpui = ">=0.1, <1.0"
rgpui-platform = ">=0.1, <1.0"

[[example]]
name = "desktop_pet"
path = "examples/desktop_pet.rs"


[lints.rust]
unexpected_cfgs = { level = "allow" }

[lints.clippy]
dbg_macro = "deny"
todo = "deny"

declare_interior_mutable_const = "deny"

redundant_clone = "deny"
disallowed_methods = "deny"

style = { level = "allow", priority = -1 }

type_complexity = "allow"
let_underscore_future = "allow"
single_range_in_vec_init = "allow"
too_many_arguments = "allow"
large_enum_variant = "allow"
nonminimal_bool = "allow"